// Code generated by mdatagen would normally populate this file. It is
// hand-written for now, matching metadata.yaml, pending real mdatagen
// wiring.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type = component.MustNewType("nats")
)

const (
	LogsStability    = component.StabilityLevelDevelopment
	MetricsStability = component.StabilityLevelDevelopment
	TracesStability  = component.StabilityLevelDevelopment
)
