resources:
- manager.yaml
kind: Kustomization
images:
- name: ghcr.io/datum-cloud/telemetry-services-operator
  newName: ghcr.io/datum-cloud/telemetry-services-operator
  newTag: latest

  # Create a config map with the configuration to use for the operator.
      # TODO: Determine why the deployment isn't getting updated to add in the hash
configMapGenerator:
- files:
  - service-config.yaml
  name: service-config
  options:
    disableNameSuffixHash: true
apiVersion: kustomize.config.k8s.io/v1beta1
