apiVersion: iam.miloapis.com/v1alpha1
kind: Role
metadata:
  name: telemetry.datumapis.com-viewer
  annotations:
    kubernetes.io/display-name: Telemetry Viewer
    kubernetes.io/description: "View access to all telemetry resources"
spec:
  launchStage: Beta
  includedPermissions:
    - telemetry.datumapis.com/exportpolicies.list
    - telemetry.datumapis.com/exportpolicies.get
    - telemetry.datumapis.com/exportpolicies.watch
