# This rule is not used by the project telemetry-services-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over telemetry.miloapis.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: telemetry-services-operator
    app.kubernetes.io/managed-by: kustomize
  name: exportpolicy-admin-role
rules:
- apiGroups:
  - telemetry.miloapis.com
  resources:
  - exportpolicies
  verbs:
  - '*'
- apiGroups:
  - telemetry.miloapis.com
  resources:
  - exportpolicies/status
  verbs:
  - get
