# This rule is not used by the project telemetry-services-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over telemetry.datumapis.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: telemetry-services-operator
    app.kubernetes.io/managed-by: kustomize
  name: exporter-admin-role
rules:
- apiGroups:
  - telemetry.datumapis.com
  resources:
  - exporters
  verbs:
  - '*'
- apiGroups:
  - telemetry.datumapis.com
  resources:
  - exporters/status
  verbs:
  - get
