---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - telemetry.datumapis.com
  resources:
  - exporters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - telemetry.datumapis.com
  resources:
  - exporters/finalizers
  verbs:
  - update
- apiGroups:
  - telemetry.datumapis.com
  resources:
  - exporters/status
  verbs:
  - get
  - patch
  - update
