api:
  enabled: false
sources:
  internal_logs:
    type: internal_logs
  internal_metrics:
    type: internal_metrics

transforms:
  component_labeler:
    type: remap
    inputs:
      - internal_metrics
    source: |
      # Only process metrics that are sources or sinks
      if .tags.component_kind != "source" && .tags.component_kind != "sink" {
        abort "Skipping non-source or non-sink component"
      }

      # The component ID will match the pattern:
      # `export-policy:<project-name>:<namespace>:<name>:<uid>:<component-name>`
      #
      # Index variables for each part
      project_name_index = 1
      namespace_index = 2
      name_index = 3
      uid_index = 4
      component_name_index = 5

      # Split the component ID into it's parts
      parts = split!(.tags.component_id, ":")



      # Only process if we have the correct number of parts.
      if length(parts) != 6 {
        abort "Skipping component with invalid component_id"
      } else if parts[0] != "export-policy" {
        abort "Skipping component that's not an export policy"
      }

      # Now we know that this component is a source or a sink for an export
      # policy.
      .tags.service_name = "telemetry.miloapis.com"
      .tags.resource_kind = "ExportPolicy"
      .tags.resource_uid = parts[uid_index]
      .tags.resource_namespace = parts[namespace_index]
      .tags.resource_name = parts[name_index]

      log(parts, level: "debug", rate_limit_secs: 0)

      # First part is always the name of the project the export policy belongs
      # to.
      .tags.resourcemanager_datumapis_com_project_name = parts[project_name_index]

      if .tags.component_kind == "source" {
        .tags.source_name = parts[component_name_index]
      } else if .tags.component_kind == "sink" {
        .tags.sink_name = parts[component_name_index]
      }

sinks:
  console:
    type: console
    inputs:
      - internal_logs
    encoding:
      codec: json

  prometheus_export:
    type: prometheus_exporter
    inputs:
      - component_labeler
    address: 0.0.0.0:9598
