apiVersion: v1
kind: ServiceAccount
metadata:
  name: vector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vector-config-watcher
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vector-config-watcher-binding
subjects:
  - kind: ServiceAccount
    name: vector
    namespace: default
roleRef:
  kind: ClusterRole
  name: vector-config-watcher
  apiGroup: rbac.authorization.k8s.io
