apiVersion: telemetry.datumapis.com/v1alpha1
kind: ExportPolicy
metadata:
  labels:
    app.kubernetes.io/name: telemetry-services-operator
    app.kubernetes.io/managed-by: kustomize
  name: exporter-sample
spec:
  # TODO(user): Add fields here
