apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1.telemetry.datumapis.com
spec:
  service:
    name: queryapi
    namespace: o11y-system
    port: 8080
  group: telemetry.datumapis.com
  version: v1
  groupPriorityMinimum: 1000
  versionPriority: 15
