apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - job.yaml

configMapGenerator:
  - name: clickhouse-migrations
    files:
      - migrations/000001_create_logs_table.up.sql
      - migrations/000001_create_logs_table.down.sql
