name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint (${{ matrix.module }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
          - operator
          - clickhouse-migrate
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ matrix.module }}/go.mod

      - name: Run linter
        uses: golangci/golangci-lint-action@v7
        with:
          version: latest
          working-directory: ${{ matrix.module }}
