name: Publish Artifacts

on:
  push:
  pull_request:
  release:
    types: ['published']

jobs:
  publish-container-image:
    permissions:
      id-token: write
      contents: read
      packages: write
      attestations: write
    uses: datum-cloud/actions/.github/workflows/publish-docker.yaml@v1.14.0
    with:
      image-name: telemetry
      registry-organization: milo-os
      context: operator
      dockerfile-path: operator/Dockerfile
      platforms: linux/amd64,linux/arm64
    secrets: inherit

  publish-clickhouse-migrate-image:
    permissions:
      id-token: write
      contents: read
      packages: write
      attestations: write
    uses: datum-cloud/actions/.github/workflows/publish-docker.yaml@v1.14.0
    with:
      image-name: telemetry-clickhouse-migrate
      registry-organization: milo-os
      context: clickhouse-migrate
      dockerfile-path: clickhouse-migrate/Dockerfile
      platforms: linux/amd64,linux/arm64
    secrets: inherit

  publish-otelcol-image:
    permissions:
      id-token: write
      contents: read
      packages: write
      attestations: write
    uses: datum-cloud/actions/.github/workflows/publish-docker.yaml@v1.14.0
    with:
      image-name: o11y/otelcol
      registry-organization: milo-os
      context: .
      dockerfile-path: otelcol/Dockerfile
      platforms: linux/amd64,linux/arm64
    secrets: inherit

  publish-kustomize-bundles:
    permissions:
      id-token: write
      contents: read
      packages: write
    uses: datum-cloud/actions/.github/workflows/publish-kustomize-bundle.yaml@v1.14.0
    with:
      bundle-name: ghcr.io/milo-os/telemetry-kustomize
      bundle-path: operator/config
      image-name: ghcr.io/milo-os/telemetry
      image-overlays: operator/config/manager
    secrets: inherit

  publish-clickhouse-migrations-kustomize:
    permissions:
      id-token: write
      contents: read
      packages: write
    uses: datum-cloud/actions/.github/workflows/publish-kustomize-bundle.yaml@v1.14.0
    with:
      bundle-name: ghcr.io/milo-os/o11y/clickhouse-migrations-kustomize
      bundle-path: config/clickhouse-migrations
      image-name: ghcr.io/milo-os/telemetry-clickhouse-migrate
      image-overlays: config/clickhouse-migrations
    secrets: inherit

  publish-edge-collectors-kustomize:
    permissions:
      id-token: write
      contents: read
      packages: write
    uses: datum-cloud/actions/.github/workflows/publish-kustomize-bundle.yaml@v1.14.0
    with:
      bundle-name: ghcr.io/milo-os/o11y/edge-collectors-kustomize
      bundle-path: config/edge-collectors
      image-name: ghcr.io/milo-os/o11y/otelcol
      image-overlays: config/edge-collectors
    secrets: inherit

  publish-o11y-sink-kustomize:
    permissions:
      id-token: write
      contents: read
      packages: write
    uses: datum-cloud/actions/.github/workflows/publish-kustomize-bundle.yaml@v1.14.0
    with:
      bundle-name: ghcr.io/milo-os/o11y/o11y-sink-kustomize
      bundle-path: config/o11y-sink
      image-name: ghcr.io/milo-os/o11y/otelcol
      image-overlays: config/o11y-sink
    secrets: inherit
